# Generated by Django 4.2.4 on 2023-08-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('date_of_upload', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('duration', models.DurationField()),
                ('is_song', models.BooleanField()),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_dashboard.user')),
            ],
        ),
    ]
