# Generated by Django 4.2.4 on 2023-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
